### ISSUE TITLE
change index so that it makes it sound like we're a design team

### ISSUE THREAD

**Issue by Scrubpai** [Electrium-Mobility/electrium-website#4]

**Comment by vivian-dai** [comment]
We needto change the descriptions on these:
![image](https://github.com/Electrium-Mobility/electrium-website/assets/38384400/5158d70e-5781-4e68-806a-4ed5888acbed)
![image](https://github.com/Electrium-Mobility/electrium-website/assets/38384400/e7e8cf5e-d3be-47ef-b95b-d738f9e0461a)
![image](https://github.com/Electrium-Mobility/electrium-website/assets/38384400/2a1ca649-ca28-4b36-a72c-5b81e80c2546)

**Comment by bk246810** [comment]
done
